run-title: "HF-CycleGAN-9"

paths:
  base: /home/bkhmsi/Documents/Datasets/CycleGAN
  save: output

  load-d-c-stream: ./output/HF-CycleGAN-9/dis_c_stream_335.h5
  load-d-r-stream: ./output/HF-CycleGAN-9/dis_r_stream_335.h5
  load-e-c-stream: ./output/HF-CycleGAN-9/ent_c_stream_335.h5

train:
  epochs: 1000
  batch-size: 4
  save-interval: 2
  lambda-cycle-loss: 10

  res-size: 64
  res-filters: 128


data:
  dataset: facades
  imsize: 256
  imchannels: 3
  extension: jpg

